[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    moononournation/GFX Library for Arduino @ 1.4.7
    mikalhart/TinyGPSPlus @ ^1.0.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BMP3XX Library @ ^2.1.4
    adafruit/Adafruit seesaw Library @ ^1.7.7
